PROBLEMAS_PSICOLOGICOS = [
    ("Depresión", 1),
    ("Ansiedad", 2),
    ("Trastorno de ansiedad generalizada (TAG)", 3),
    ("Trastorno obsesivo-compulsivo (TOC)", 4),
    ("Trastorno de pánico", 5),
    ("Fobias específicas", 6),
    ("Trastorno de estrés postraumático (TEPT)", 7),
    ("Trastorno de la personalidad borderline (TLP)", 8),
    ("Trastorno de la personalidad narcisista (TPN)", 9),
    ("Trastorno de la personalidad antisocial (TPA)", 10),
    ("Trastorno de la personalidad esquizoide (TPE)", 11),
    ("Trastorno de la personalidad evitativa (TPE)", 12),
    ("Trastorno de la personalidad dependiente (TPD)", 13),
    ("Trastorno de la alimentación (anorexia, bulimia, trastorno por atracón)", 14),
    ("Trastorno de sueño (insomnio, narcolepsia)", 15),
    ("Trastorno por déficit de atención e hiperactividad (TDAH)", 16),
    ("Trastornos del espectro autista (TEA)", 17),
    ("Trastornos del estado de ánimo bipolar", 18),
    ("Trastorno límite de la personalidad (TLP)", 19),
    ("Trastorno dismórfico corporal (TDC)", 20),
    ("Trastorno de la conducta alimentaria selectiva", 21),
    ("Trastorno de la conducta", 22),
    ("Trastorno explosivo intermitente (TEI)", 23),
    ("Trastorno de la rumiación", 24),
    ("Trastorno de control de impulsos", 25),
    ("Trastorno del juego", 26),
    ("Trastorno del espectro de la esquizofrenia", 27),
    ("Trastorno del espectro de la esquizofrenia residual", 28),
    ("Trastorno del espectro de la esquizofrenia catatónica", 29),
    ("Trastorno de la conducta sexual", 30),
    ("Trastorno de la identidad de género", 31),
    ("Trastorno de estrés agudo", 32),
    ("Trastorno de la somatización", 33),
    ("Trastorno de somatización facticia", 34),
    ("Trastorno de la eliminación (encopresis, enuresis)", 35),
    ("Trastorno de ansiedad social (fobia social)", 36),
    ("Trastorno de la ensoñación excesiva", 37),
    ("Trastorno de la adaptación", 38),
    ("Trastorno de la comunicación social (pragmático)", 39),
    ("Trastorno de la eliminación del sueño (insomnio)", 40),
    ("Trastorno de la excitación sexual", 41),
    ("Trastorno de la fase de transición del sueño-vigilia", 42),
    ("Trastorno de la fase del sueño-vigilia", 43),
    ("Trastorno de la identidad sexual", 44),
    ("Trastorno de la eliminación nocturna (insomnio)", 45),
    ("Trastorno de la memoria disociativa", 46),
    ("Trastorno de la percepción sensorial", 47),
    ("Trastorno de la reserva de fase del sueño-vigilia", 48),
    ("Trastorno de la reserva del sueño", 49),
    ("Trastorno de la vinculación", 50)
]
